# fly --target spring login --concourse-url https://ci.spring.io
# echo passphrase: <secret> > credentials.yml
# fly --target spring set-pipeline --config pipeline.yml --pipeline gs-rest-service --load-vars-from credentials.yml
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/dsyer/gs-rest-service.git
    branch: gpg
- name: keys
  type: git
  source:
    uri: https://github.com/dsyer/concourse-keys.git
  
jobs:
- name: build
  plan:
  - get: keys
  - get: source
    trigger: true
  - aggregate:
    - task: maven
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: maven, tag: 3.5.0-jdk-8}
        inputs:
          - name: keys
          - name: source
        run:
          dir: source
          path: ./build.sh
      params:
        TERM: -dumb
        passphrase: {{passphrase}}
    - task: gradle
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: java, tag: '8'}
        inputs:
          - name: source
        run:
          dir: source/complete
          path: ./gradlew
          args: [build]
      params:
        TERM: -dumb
        GRADLE_OPTS: -Dorg.gradle.native=false