# fly --target spring login --concourse-url https://ci.spring.io
# fly --target spring set-pipeline --config pipeline.yml --pipeline gs-rest-service
---
resources:
- name: source
  type: git
  source:
    uri: https://github.com/spring-guides/gs-rest-service.git
  
jobs:
- name: build
  plan:
  - get: source
    trigger: true
  - aggregate:
    - task: maven
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: 
            repository: springio/maven-base
        inputs:
          - name: source
        run:
          dir: source/complete
          path: ./mvnw
          args: [install]
      params:
        TERM: -dumb
    - task: gradle
      config:
        platform: linux
        image_resource:
          type: docker-image
          source:
            repository: springio/gradle-base
        inputs:
          - name: source
        run:
          dir: source/complete
          path: ./gradlew
          args: [build]
      params:
        TERM: -dumb
        GRADLE_OPTS: -Dorg.gradle.native=false